"""Criar tabela Revista

Revision ID: 30c6759afd70
Revises: d0a79a6c8f11
Create Date: 2026-08-22 12:04:55.734592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c6759afd70'
down_revision: Union[str, Sequence[str], None] = 'd0a79a6c8f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issn', sa.String(length=14), nullable=False),
    sa.Column('edicao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id', 'issn'),
    sa.UniqueConstraint('issn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revista')
    # ### end Alembic commands ###
