"""Criar tabelas Livro e Autor

Revision ID: 9fe61b7e95d2
Revises: 8c59956c6599
Create Date: 2026-08-22 11:52:58.268191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe61b7e95d2'
down_revision: Union[str, Sequence[str], None] = '8c59956c6599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
